config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  get 'profile', to: 'tasks#index'
  resources :tasks, :except => :index do
    member do
      post 'start'
      post 'finish'
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :task

  has_attached_file :file
  do_not_validate_attachment_file_type :file

  validates :task, presence: true
  validates :file, attachment_presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :attachments

  accepts_nested_attributes_for :attachments, :reject_if => :all_blank, :allow_destroy => true

  state_machine :state, :initial => :new do
    state :started
    state :finished

    event :start do
      transition :new => :started
    end

    event :finish do
      transition :started => :finished
    end
  end

  before_validation :on => :create do
    initialize_state_machines(:dynamic => :force)
  end

  validates :name, :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :with => :exception

  rescue_from(ActiveRecord::RecordNotFound) do
    render_404
  end

  protected

  def render_404
    render status: 404, layout: false
  end

  def render_403
    render status: 403, layout: false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.includes(:user)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_task, only: [:show, :edit, :update, :destroy, :start, :finish]
  before_action :check_access, only: [:edit, :update, :destroy, :start, :finish]

  def index
    @tasks = default_scope
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user

    if @task.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to profile_path
  end

  def start
    if @task.can_start?
      @task.start!
      redirect_to task_path(@task)
    else
      render_403
    end
  end

  def finish
    if @task.can_finish?
      @task.finish!
      redirect_to task_path(@task)
    else
      render_403
    end
  end

  private

  def default_scope
    Task.where(user: current_user)
  end

  def find_task
    @task = default_scope.find(params[:id])
  end

  def check_access
    render_403 unless @task.user == current_user
  end

  def task_params
    params.require(:task).permit(:name, :description, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  TASK_STATE_LABELS = {
    new: 'warning',
    started: 'info',
    finished: 'success'
  }.freeze

  def show_task_state(task)
    state = Task.human_attribute_name("state.#{task.state}")
    css_class = TASK_STATE_LABELS[task.state_name]
    "<span class='label label-#{css_class}'>#{state}</span>"
  end
end

app/views/application/_header.html.slim
#header
  .navbar.navbar-default
    .container
      .navbar-header
        a class="navbar-brand" href=root_path
          = t(:app_name)
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li == link_to t(:profile), profile_path, class: 'profile'
          li == link_to t(:logout), destroy_user_session_path, :class => 'logout', :method => :delete
        - else
          li == link_to t(:login), new_user_session_path, class: 'login'

app/views/home/index.html.slim
h1 = t(:tasks)

- if @tasks.present?
  table#tasks.table.table-hover
    thead
      tr
        th.name = Task.human_attribute_name(:name)
        th.user = Task.human_attribute_name(:user)
    tbody
    - @tasks.each do |task|
      tr.task
        td.name = task.name
        td.user = task.user.email
- else
  .alert.alert-info
    = t(:tasks_not_found)

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t(:app_name)
    == stylesheet_link_tag 'application', media: 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
    == yield :head
  body
    == render partial: 'application/header'

    .container
      - if notice
        .alert.alert-info = notice
      - if alert
        .alert.alert-warning = alert

    #content.container
      == yield

app/views/tasks/_attachment_fields.html.slim
.nested-fields.form-group
  .form-inline
    - if f.object.new_record?
      == f.file_field :file, class: 'form-control'
    - else
      .btn.btn-default = f.object.file_file_name
    ==< link_to_remove_association f, class: 'btn btn-danger', title: t(:destroy) do
      .glyphicon.glyphicon-remove

app/views/tasks/_form.html.slim
= form_for task, multipart: true do |form|
  - if task.errors.any?
    .alert.alert-danger
      ul
        - task.errors.full_messages.each do |message|
          li = message

  .form-group
    == form.label :name
    == form.text_field :name, class: 'form-control'

  .form-group
    == form.label :description
    == form.text_field :description, class: 'form-control'

  .panel.panel-default
    .panel-heading = t(:attachments)
    .panel-body
      = form.fields_for :attachments do |attachment|
        = render 'attachment_fields', f: attachment
      .links
        = link_to_add_association t(:add_attachment), form, :attachments, class: 'btn btn-success'

  .form-group
    == form.submit t(:save), class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 = t(:editing_task)

== render 'form', task: @task

== link_to t(:back), profile_path, class: 'btn btn-default'

app/views/tasks/index.html.slim
h1 = t(:profile)

- if @tasks.present?
  table#tasks.table.table-hover
    thead
      tr
        th.name = Task.human_attribute_name(:name)
        th.state = Task.human_attribute_name(:state)
        th.description = Task.human_attribute_name(:description)
        th.actions
    tbody
    - @tasks.each do |task|
      tr.task
        td.name == link_to task.name, task
        td.state == show_task_state(task)
        td.description = task.description
        td
          == link_to t(:edit), edit_task_path(task), class: 'btn btn-primary btn-xs'
          ==< link_to t(:destroy), task, :class => 'btn btn-danger btn-xs',
                     :method => :delete, :data => { confirm: t(:are_you_sure) }
- else
  .alert.alert-info
    = t(:tasks_not_found)

== link_to t(:new_task), new_task_path, class: 'btn btn-primary'

app/views/tasks/new.html.slim
h1 = t(:new_task)

== render 'form', task: @task

== link_to t(:back), profile_path, class: 'btn btn-default'

app/views/tasks/show.html.slim
h1 = @task.name

p.state #{Task.human_attribute_name(:state)}: #{{show_task_state(@task)}}
p.description #{Task.human_attribute_name(:description)}: #{@task.description}

- if @task.attachments.present?
  .panel.panel-default.attachments
    .panel-heading = t(:attachments)
    .panel-body
      ul
        - @task.attachments.each do |attachment|
          li == link_to attachment.file_file_name, attachment.file.url

- if @task.can_start?
  == link_to t(:start_task), start_task_path(@task), method: 'post', class: 'btn btn-info'
- if @task.can_finish?
  == link_to t(:finish_task), finish_task_path(@task), method: 'post', class: 'btn btn-success'

==< link_to t(:edit), edit_task_path(@task), class: 'btn btn-primary'
==< link_to t(:back), profile_path, class: 'btn btn-default'